@startuml
left to right direction
actor Customer
actor Employee
actor Provider

usecase "Registro" as UC1
usecase "Login" as UC2
usecase "View Vehicle Catalog" as UC3
usecase "Make Reservation" as UC4
usecase "Manage Reservations" as UC5
usecase "Manage Vehicles" as UC6
usecase "Manage Invoices" as UC7
usecase "Manage Reviews" as UC8
usecase "Manage Brands and Models" as UC9

Customer --> (UC1)
Customer --> (UC2)
Customer --> (UC3)
Customer --> (UC4)
Customer --> (UC5)
Customer --> (UC8)
Employee --> (UC1)
Employee --> (UC2)
Employee --> (UC3)
Employee --> (UC4)
Employee --> (UC5)
Employee --> (UC6)
Employee --> (UC7)
Employee --> (UC8)
Employee --> (UC9)
Provider --> (UC6)
Provider --> (UC7)
Provider --> (UC9)

@enduml
